language: node_js
node_js:
  - "10"

dist: trusty

branches:
  only:
    - master
    - release/*
    - feature/*

script:
  - cd frontend
  - cd kitten-experience
  - npm ci
  - grunt build:standalone
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: frontend/kitten-experience/dist
  verbose: true
  keep-history: true
  on:
    branch: master
